name: ubk
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - altair=4.1.0
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.4
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - daal4py=2023.1.1
  - dal=2023.1.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - glib=2.69.1
  - glog=0.5.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.15.0
  - ipython=8.13.2
  - ipywidgets=8.0.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.88.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.5.1
  - plotly=5.9.0
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydeck=0.7.1
  - pygments=2.15.1
  - pympler=0.9
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7
  - pywin32=305
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - requests=2.29.0
  - rich=13.3.5
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.1.1
  - scipy=1.10.1
  - semver=2.13.0
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.6.2
  - streamlit=1.16.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - tzlocal=2.1
  - urllib3=1.26.15
  - utf8proc=2.6.1
  - validators=0.18.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.6
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
