# --------------------------------- Constants -------------------------------- #
constants:
  average_productivity: 0.238 # This value is taken from Penn World Table 
  add_income_loss: false
  calc_exposure_params:
    pov_bias_rnd_distr: uniform
    pov_bias_rnd_high: 1.5
    pov_bias_rnd_low: 0.5
  consump_util: 1.5
  country: Saint Lucia
  ident_affected_params:
    delta_pct: 0.05
    distr: uniform
    high: 1.0
    low: 0
    num_masks: 10000
  discount_rate: 0.04
  districts:
  - AnseLaRayeCanaries
  - Castries
  - Choiseul
  - Dennery
  - Gros Islet
  - Laborie
  - Micoud
  - Soufriere
  - Vieuxfort
  est_sav_params:
    mean_noise_distr: uniform
    mean_noise_high: 5
    mean_noise_low: 0
    noise_distr: normal
    noise_scale: 2.5
    sav_clip_max: 1.0
    sav_clip_min: 0.1
  income_and_expenditure_growth: 0.01
  indigence_line: 2123
  is_vuln_random: false
  atol: 100000 # Abs tolerance for matching asset stock of damage and household survey data sets
  min_representative_households: 400
  years_to_recover: 10
  lambda_increment: 0.01
  poverty_bias: 1.0
  poverty_line: 6443
  return_period: 100
  saving_rate: 0.02385
  save_households: False
  scale: district
  assign_vuln_params:
    vuln_init_distr: uniform
    vuln_init_low: 1.15 # default 1.4
    vuln_init_high: 0.85 # default 0.6
    vuln_init_thresh: 0.99
    vuln_rnd_distr: uniform
    vuln_rnd_high: 0.9
    vuln_rnd_low: 0.01

# ------------------------------- Policy levers ------------------------------ #
# The naming convention is: <target group> + <top up percentage>
# The following target groups are currently specified: all, poor, poor_near_poor1.25, poor_near_poor2.0
# There are no limitations on the top-up percentage
# Top-up percentage is added to `aeexp` or adult equivalent expenditure of a household
# It is applied as a multiplier to `keff*v`: households['aeexp'] += households.eval('keff*v') * top_up / 100
# where `v` is the vulnerability of the household and `keff` is the effective capital stock
levers:
  0: all+0
  1: all+10
  2: all+30
  3: all+50
  4: all+100
  5: poor+0
  6: poor+10
  7: poor+30
  8: poor+50
  9: poor+100
  10: poor_near_poor1.25+0
  11: poor_near_poor1.25+10
  12: poor_near_poor1.25+30
  13: poor_near_poor1.25+50
  14: poor_near_poor1.25+100
  15: poor_near_poor2.0+0
  16: poor_near_poor2.0+10
  17: poor_near_poor2.0+30
  18: poor_near_poor2.0+50
  19: poor_near_poor2.0+100

# ------------------------------- Uncertainties ------------------------------ #
uncertainties:
  consump_util:
  - 1.0
  - 1.5
  discount_rate:
  - 0.04
  - 0.07
  income_and_expenditure_growth:
  - 0.01
  - 0.03
  poverty_line:
  - 1.0
  - 1.5